### ISSUE TITLE
Machine-parseable license

### ISSUE THREAD

**Issue by vorner** [kbknapp/term_size-rs#13]
Would it be possible to specify the license in the `Cargo.toml` as:

```
license = "MIT/Apache-2.0"
```

This seems to be the preferred way (according to http://doc.crates.io/manifest.html#package-metadata) and is machine parseable, unlike the current "MIT OR Apache-2.0", which various tools (like cargo-lichking) can't recognize.

**Comment by kbknapp** [comment]
I'm good with it. I'm not sure where I got the `MIT OR Apache-2.0` from...?
